### PR TITLE
Fix native target builds on macos

### PR DESCRIPTION
**Pull request by g-oikonomou**
This PR fixes the bug shown below when trying to build `rpl-border-router` for `TARGET=native` on macos

```
~/contiki-ng/examples/rpl-border-router (develop)$ make TARGET=native
  MKDIR     build/native/obj
  CC        ../../arch/platform/native/./platform.c
  CC        ../../arch/platform/native/./clock.c
  CC        ../../arch/platform/native/dev/xmem.c
  CC        ../../arch/platform/native/./cfs-posix.c
  CC        ../../arch/platform/native/./cfs-posix-dir.c
  CC        ../../arch/platform/native/dev/buttons.c
  CC        ../../arch/cpu/native/net/tun6-net.c
../../arch/cpu/native/net/tun6-net.c:69:27: error: use of undeclared identifier 'IFNAMSIZ'
static char config_tundev[IFNAMSIZ + 1] = "tun0";
                          ^
1 error generated.
make: *** [build/native/obj/tun6-net.o] Error 1
```

### CODE REVIEW

**Comment by g-oikonomou** [comment]
Actually that also affects hello world and I think pretty much everything

**Comment by alexstanoev** [comment]
Fixes the build on macOS 11.2 and doesn't cause issues on Linux

**Review by alexstanoev — APPROVED** [review]

**Comment by g-oikonomou** [comment]
```
$ sudo ../../tools/serial-io/tunslip6 -s /dev/tty.usbmodemL400A0241 fd00::1/64
Password:
********SLIP started on ``/dev/tty.usbmodemL400A0241''
opened tun device ``/dev/utun10''
ifconfig utun10 inet6 mtu 1500 up
ifconfig utun10 inet6 fd00::1/64 add
sysctl -w net.inet6.ip6.forwarding=1
net.inet6.ip6.forwarding: 0 -> 1
ifconfig utun10

utun10: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet6 fe80::8e85:90ff:fe07:d9db%utun10 prefixlen 64 scopeid 0xf 
	inet6 fd00::1 prefixlen 64 
	nd6 options=201<PERFORMNUD,DAD>
[INFO: BR        ] Waiting for prefix
*** Address:fd00::1 => fd00:0000:0000:0000
[INFO: BR        ] Waiting for prefix
[INFO: BR        ] Server IPv6 addresses:
[INFO: BR        ]   fd00::212:4b00:bc9:6b81
[INFO: BR        ]   fe80::212:4b00:bc9:6b81
```

```
$ ifconfig utun10
utun10: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 1500
	inet6 fe80::8e85:90ff:fe07:d9db%utun10 prefixlen 64 scopeid 0xf 
	inet6 fd00::1 prefixlen 64 
	nd6 options=201<PERFORMNUD,DAD>
```

```
$ ping6 fd00::212:4b00:bc9:6b81
PING6(56=40+8+8 bytes) fd00::1 --> fd00::212:4b00:bc9:6b81
16 bytes from fd00::212:4b00:bc9:6b81, icmp_seq=0 hlim=64 time=11.183 ms
16 bytes from fd00::212:4b00:bc9:6b81, icmp_seq=1 hlim=64 time=10.978 ms
16 bytes from fd00::212:4b00:bc9:6b81, icmp_seq=2 hlim=64 time=11.077 ms
16 bytes from fd00::212:4b00:bc9:6b81, icmp_seq=3 hlim=64 time=11.698 ms
--- fd00::212:4b00:bc9:6b81 ping6 statistics ---
4 packets transmitted, 4 packets received, 0.0% packet loss
round-trip min/avg/max/std-dev = 10.978/11.234/11.698/0.278 ms
```
